### PR TITLE
Fix: FindName now matches partial name, matching UG behaviour

### LINKED ISSUE #172: [PE-D][Tester B] Find name feature: Finding using a part of a word does not return the whole word as a possible result
I created the person with name Jackson below.

Thereafter, I tried to find this person using `find n/jackson` but there were 0 results listed as shown below. This seems to contradict what was stated in the UG which is: Partial words can be matched only if the whole name is included. e.g. Jack will match Jackson, but Jackson won’t match Jack. What I would suggest is to clarify in the UG like something under the find address portion: Words can be matched only if the whole address is included. e.g. Tamp won’t match Tampines 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Sampy147/ped#2

### PR DESCRIPTION
**Pull request by isanidiot**
closes #172  and #148

### CODE REVIEW

File: src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java [hunk 1]
```diff
@@ -18,7 +16,7 @@ public NameContainsKeywordsPredicate(List<String> keywords) {
     @Override
     public boolean test(Person person) {
         return keywords.stream()
-                .anyMatch(keyword -> StringUtil.containsWordIgnoreCase(person.getName().getFullName(), keyword));
+                .anyMatch(keyword -> person.getName().getFullName().toLowerCase().contains(keyword.toLowerCase()));
```
Comment (ReaganTan00) [inline src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java:19]: Not too sure why the previous version does not work but trust that this works as intended

File: src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java [hunk 2]
```diff
@@ -54,6 +54,10 @@ public void test_nameContainsKeywords_returnsTrue() {
         predicate = new NameContainsKeywordsPredicate(Arrays.asList("Bob", "Carol"));
         assertTrue(predicate.test(new PersonBuilder().withName("Alice Carol").build()));
 
+        // Partially matching keyword
+        predicate = new NameContainsKeywordsPredicate(Arrays.asList("Ella", "Carol"));
+        assertTrue(predicate.test(new PersonBuilder().withName("Bella Hadid").build()));
+
```
Comment (ReaganTan00) [inline src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java:60]: Test case to verify that it works

**Review by ReaganTan00 — APPROVED** [review]
LGTM
